name: islami_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  audioplayers: ^6.0.0
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/files/

  uses-material-design: true

